### PR TITLE
fixed adaptive sampler norm phi idx

### PR DESCRIPTION
**Pull request by nolanstr**
I included a method for the adaptive sampler that checks each proposed new phi value against the current phi sequence and the required phi. 

If the required phi was already in the phi sequence, it returns phi, elif the proposed phi is larger than the required phi, then it returns the required phi, else it returns the proposed phi.

### CODE REVIEW

**Comment by peleser** [comment]
Hey @nolanstr -- thanks. Can you explain what the bloom sampler is doing?

**Comment by nolanstr** [comment]
Hey @peleser, the bloom sampler was an idea I had a while back for creating a better initial set of particles by growing the size of particles by some multiplier and mutating them with the mcmc kernel before sampling the new initial set of particles from this population. I haven't done any more work with it for quite a long time. Where are you seeing this?

**Comment by peleser** [comment]
It looks like you added the bloom sampler as part of this pull request. No worries -- I'm going to just close this for now since it sounds like it's something you didn't mean to push. The other portion of the pull request addresses the tracking of required phi values, but I think that the current develop code does this now, so no need to modify. Let me know if you run into any troubles with the current develop version. Thanks!

**Comment by nolanstr** [comment]
Oh, shoot, yeah, my bad. Thanks, Pat! I'm honestly quite surprised that that code was still in there.

**Pull request closed without merging**
